title: The World of Biochemistry
desciption: >
  DNA is software, protein is hardware, and the environment is the operating system.
email: chen-sq23@mails.tsinghua.edu.cn
baseurl: "/biochem_atlas" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://githuadream.github.io" # the base hostname & protocol for your site
markdown: kramdown
page_excerpts: true
favicon: "/img/symbol.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
